name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

# Note that when you see patterns like "ref: test-data/v2/basic" within this workflow,
# these refer to "test-data" branches on this actions/checkout repo.
# (For example, test-data/v2/basic -> https://github.com/actions/checkout/tree/test-data/v2/basic)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - uses: actions/checkout@v6
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test
      - name: Verify no unstaged changes
        run: __test__/verify-no-unstaged-changes.sh

  success:
    needs:
      - build
    permissions:
      contents: write
      deployments: write
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Set up Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: 'package.json'
      - name: Install Semantic Release
        run: npm install
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: npx semantic-release
